const vscode = require("vscode");

/**
 * Builder Startup Extension
 *
 * Automatically configures the workspace layout for non-technical builders:
 * 1. Opens the Claude Code secondary sidebar (right panel with chat)
 * 2. Opens the WELCOME.md guide as a markdown preview in the center editor
 *
 * The dev server is started separately by a VS Code task (runOn: folderOpen)
 * generated by entrypoint.sh.
 */

const WELCOME_FILE = "/home/coder/project/WELCOME.md";
const STARTUP_DELAY_MS = 5000; // Wait for extensions + dev server to initialize

async function activate(context) {
  // Wait for other extensions to fully load
  await sleep(STARTUP_DELAY_MS);

  // 1. Open the welcome guide in the center editor
  await openWelcomePage();

  // 2. Open Claude Code in the secondary sidebar (right panel)
  await openClaudeSidebar();
}

async function openClaudeSidebar() {
  // Target the secondary sidebar first (right panel — where the real chat lives)
  // code-server 4.118+ supports secondary sidebar, so Claude registers there
  const commands = [
    "workbench.view.extension.claude-sidebar-secondary",
    "claudeVSCodeSidebarSecondary.focus",
    // Fallbacks for older code-server without secondary sidebar support
    "workbench.view.extension.claude-sidebar",
    "claudeVSCodeSidebar.focus",
  ];

  for (const cmd of commands) {
    try {
      await vscode.commands.executeCommand(cmd);
      return; // Success — stop trying
    } catch {
      // Command not available, try next
    }
  }
  console.warn("[builder-startup] Could not open Claude Code sidebar");
}

async function openWelcomePage() {
  try {
    const uri = vscode.Uri.file(WELCOME_FILE);
    // Open the markdown file as a preview (rendered, not raw)
    await vscode.commands.executeCommand("markdown.showPreview", uri);
  } catch {
    console.warn("[builder-startup] Could not open WELCOME.md preview");
  }
}

function sleep(ms) {
  return new Promise((resolve) => setTimeout(resolve, ms));
}

function deactivate() {}

module.exports = { activate, deactivate };
